version: "3"
services: 
    application:
        build: .
        container_name: go-docker-learn
        ports:
            - "8080:8080"
        environment: 
            - "PORT=8080"
            - "CHUNK_SIZE=1048576"
        volumes: 
            - ./application/data:/application/data
            - ./application/templates:/application/templates